version: '0'
services:
  server_rag:
    build: aisearchservice/
    command: python aisearchservice/server/aisearch.py
    ports:
      - 50000:50000
    volumes:
      - /home/esguser/aibot:/home/jovyan/
    healthcheck:
      test: curl --fail -s http://localhost:50000/creds || exit 1
      interval: 1m
      timeout: 1m
  client_rag:
    build: aisearchservice/
    command: streamlit run aisearchservice/app/Main_page.py --server.port 50001 --browser.gatherUsageStats False
    ports:
      - 50001:50001
    depends_on:
      - server_rag
    volumes:
      - /home/esguser/aibot:/home/jovyan/
    healthcheck:
      test: curl --fail -s http://localhost:50001 || exit 1
      interval: 1m
      timeout: 1m