version: '0'
services:
  server_rag:
    build: aisearchservice/
    command: python aisearchservice/server/aisearch.py
    ports:
      - 50000:50000
    volumes:
      - /home/esguser/aibot:/home/jovyan/
    healthcheck:
      test: ./aisearchservice/healthchecksrv.sh
      interval: 1m
      timeout: 1m
  client_rag:
    build: aisearchservice/
    command: streamlit run aisearchservice/app/Main_page.py --server.port 50001 --browser.gatherUsageStats False
    ports:
      - 50001:50001
    depends_on:
      - server_rag
    volumes:
      - /home/esguser/aibot:/home/jovyan/
    healthcheck:
      test: ./aisearchservice/healthcheckclnt.sh
      interval: 1m
      timeout: 1m
  client_bot:
    build: aisearchservice/
    command: python aisearchservice/bot/tgbot.py
    depends_on:
      - server_rag
    volumes:
      - /home/esguser/aibot:/home/jovyan/
    healthcheck:
      disable: true